set $red       #E67E80
set $yellow    #DBBC7F
set $green     #A7C080
set $blue      #7FBBB3
set $aqua      #83C092
set $text      #D3C6AA
set $background      #333C43

# target                 title     bg    text      indicator    border
client.focused           $blue   $background $text  $yellow $green
client.focused_inactive  $background $background  $text    $background $background
client.unfocused         $background $background  $text    $background $background
client.urgent            $background    $background  $text   $background  $background
client.placeholder       $background $background  $text    $background  $background
client.background        $background

